import {createFetchActions} from './action_creators/actionCreator';

export const TOURNAMENTS_FETCH_SUCCESS = 'TOURNAMENTS_FETCH_SUCCESS';
export const TOURNAMENTS_FETCH_FAILED = 'TOURNAMENTS_FETCH_FAILED';
export const TOURNAMENTS_FETCH_PROGRESS = 'TOURNAMENTS_FETCH_PROGRESS';
export const TOURNAMENTS_FETCH_REQUESTED = 'TOURNAMENTS_FETCH_REQUESTED';
export const TOURNAMENTS_LOADING = 'TOURNAMENTS_LOADING';

export const [
  SOLUTION_FETCH,
  SOLUTION_FETCH_SUCCESS,
  SOLUTION_FETCH_FAILED
] = createFetchActions('SOLUTION_FETCH');

