export const TOURNAMENTS_FETCH_SUCCESS = 'TOURNAMENTS_FETCH_SUCCESS';
export const TOURNAMENTS_FETCH_FAILED = 'TOURNAMENTS_FETCH_FAILED';
export const TOURNAMENTS_FETCH_PROGRESS = 'TOURNAMENTS_FETCH_PROGRESS';
export const TOURNAMENTS_FETCH_REQUESTED = 'TOURNAMENTS_FETCH_REQUESTED';
